//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderId { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string ContentPayment { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public string OrderCode { get; set; }
    
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
