//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentExpVat
    {
        public int PaymentExpVatId { get; set; }
        public string OrderCode { get; set; }
        public string CompanyName { get; set; }
        public string TaxCode { get; set; }
        public string BuyerName { get; set; }
        public string CompanyAddress { get; set; }
        public string ReceiveBillAddress { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string Email { get; set; }
    }
}
